### ISSUE TITLE
DIP fails to compile.

### ISSUE THREAD

**Issue by caoliver** [captainssounds/vcv-CaptainsSounds#25]
HuovilainenMoogFilter.hpp tries to bring in util.h which doesn't exist.

The only dependency I see is for MOOG_PI which looks like a quad precision pi constant.

**Comment by mikeallisonJS** [comment]
do a 'make dep' to install the dependency

**Comment by mikeallisonJS** [comment]
also, be sure you have the wget package installed. (most do, but I had to add it to my git builds)

**Comment by caoliver** [comment]
Don't you think this should get handled as a submodule init.
Most (all other?) plugin kits fetch their dependencies during: git submodule update --init --recursive without an additional make dep.

**Comment by mikeallisonJS** [comment]
I have not come across any examples of this in other modules (not that I've seen a lot). I based mine on the same dependency pattern as the Fundamental modules.

Do you have an example of a plugin using this approach?

**Comment by mikeallisonJS** [comment]
closing for lack of response. feel free to update with example

**Comment by caoliver** [comment]
Sorry to be late.  Look at AudibleInstruments.  That pulls eurorack as a submodule.
