### ISSUE TITLE
DBUG crashes when placed to the right of most modules

### ISSUE THREAD

**Issue by curlymorphic** [captainssounds/vcv-CaptainsSounds#35]
V1.0.6
OS Ubuntu 20.4
Rack v 1.6

When I place or drag DBug  to the right-hand side of any module I have tested with, VCV rack crashes, with the standard "VCV RACK has crashed. see log.txt for details" dialog box.

[log.txt](https://github.com/captainssounds/vcv-CaptainsSounds/files/4917022/log.txt)

**Comment by mikeallisonJS** [comment]
Is this with plugins setup to send the DBugMessage through the extender? Currently, that is the only case that always seems to work. It's better, but still breaks.

If not, I have yet to find a foolproof way of identifying them. I'm wholly open to suggestions and am still working on it, but it's hard to account for every possible thing another plugin's internals create.

**Comment by curlymorphic** [comment]
I have not tested this with modules that use the extender. This was initially brought to my attention via a bug report on the Modular Fungi repo.  

I have not looked at your code to make any suggestions, but I shall try to take the time to do so.

**Comment by curlymorphic** [comment]
Mike, do you have a module that works with Dbug that I could test with please?

**Comment by mikeallisonJS** [comment]
Sure thing, if you have the Captains Sounds modules installed, there is a pre-built testing rack for all of the modules, including DBug

**Comment by mikeallisonJS** [comment]
Fixed in 1.0.7 release. Awaiting library update
